### ISSUE TITLE
Dataverse debe cumplir en menos sprints

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1666]
**Problema**: Ahora toman 4-6 sprints, con la mayoria de [DEV012 tomando 6](https://docs.google.com/spreadsheets/d/1JhpBxpHQQ_tt0cD7xDpPkc6X9dpkHh1PE7ph6qYLVGw/edit#gid=1868031241). Queremos que eso seria un minoridad y la mayoria tomen 4-5 sprints, paracedio a Data Lovers .

_Nota_: hay que verificar [donde podemos sacar este data](https://lookerstudio.google.com/u/0/reporting/8b59a6e8-f48b-4ae4-abc9-97171ddd1ed7/page/p_ipggtxlz0c?s=hsjPQARBzFk) de sprints tomado por proyecto en comparison de Data Lovers.

**Hipotesis**: Estudiantes estan bloqueado por los tests de OAs (algunas de metodos de arreglo) y e2e en lugar de usarlos como herramienta para investigar y darse cuenta a los OAs pendientes.

**Soluciones**:

- [ ] Cambia el lenguaje de la seccion Pedir Project Feedback #1638 
- [ ] Ajustamos algunos tests de OAs #1646
- [x] #1667
- [ ] Nosotros como coaches comunicamos en os kickoffs y Q+As el tema de tests con las estudiantes, como usarlos para ayudarles y no impedirles

Otras ideas de largo plazo: cambios a como presentamos el microdata y otros instucciones de proyecto, Hitos de proyecto, e2e opcional
